/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AccusativeImport } from './routes/accusative'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const AccusativeRoute = AccusativeImport.update({
  id: '/accusative',
  path: '/accusative',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/accusative': {
      id: '/accusative'
      path: '/accusative'
      fullPath: '/accusative'
      preLoaderRoute: typeof AccusativeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accusative': typeof AccusativeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accusative': typeof AccusativeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/accusative': typeof AccusativeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accusative'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accusative'
  id: '__root__' | '/' | '/accusative'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccusativeRoute: typeof AccusativeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccusativeRoute: AccusativeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/accusative"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/accusative": {
      "filePath": "accusative.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
