/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ScoreboardImport } from "./routes/scoreboard";
import { Route as AccusativeImport } from "./routes/accusative";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const ScoreboardRoute = ScoreboardImport.update({
  id: "/scoreboard",
  path: "/scoreboard",
  getParentRoute: () => rootRoute,
} as any);

const AccusativeRoute = AccusativeImport.update({
  id: "/accusative",
  path: "/accusative",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/accusative": {
      id: "/accusative";
      path: "/accusative";
      fullPath: "/accusative";
      preLoaderRoute: typeof AccusativeImport;
      parentRoute: typeof rootRoute;
    };
    "/scoreboard": {
      id: "/scoreboard";
      path: "/scoreboard";
      fullPath: "/scoreboard";
      preLoaderRoute: typeof ScoreboardImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/accusative": typeof AccusativeRoute;
  "/scoreboard": typeof ScoreboardRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/accusative": typeof AccusativeRoute;
  "/scoreboard": typeof ScoreboardRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/accusative": typeof AccusativeRoute;
  "/scoreboard": typeof ScoreboardRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/accusative" | "/scoreboard";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/accusative" | "/scoreboard";
  id: "__root__" | "/" | "/accusative" | "/scoreboard";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AccusativeRoute: typeof AccusativeRoute;
  ScoreboardRoute: typeof ScoreboardRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccusativeRoute: AccusativeRoute,
  ScoreboardRoute: ScoreboardRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/accusative",
        "/scoreboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/accusative": {
      "filePath": "accusative.tsx"
    },
    "/scoreboard": {
      "filePath": "scoreboard.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
