import { AccusativeChallengeQuestions } from "./AccusativeChallenge.types";

export const accusativeChallengeQuestions: AccusativeChallengeQuestions = [
  { noun: "kutya", correctAnswer: "kutyát", translation: "Dog" },
  { noun: "macska", correctAnswer: "macskát", translation: "Cat" },
  { noun: "autó", correctAnswer: "autót", translation: "Car" },
  { noun: "ház", correctAnswer: "házat", translation: "House" },
  { noun: "szám", correctAnswer: "számot", translation: "Number" },
  { noun: "könyv", correctAnswer: "könyvet", translation: "Book" },
  { noun: "táska", correctAnswer: "táskát", translation: "Bag" },
  { noun: "szék", correctAnswer: "széket", translation: "Chair" },
  { noun: "asztal", correctAnswer: "asztalt", translation: "Table" },
  { noun: "ember", correctAnswer: "embert", translation: "Person" },
  { noun: "fa", correctAnswer: "fát", translation: "Tree" },
  { noun: "kutatás", correctAnswer: "kutatást", translation: "Research" },
  { noun: "ruha", correctAnswer: "ruhát", translation: "Clothes" },
  { noun: "óra", correctAnswer: "órát", translation: "Clock" },
  {
    noun: "számítógép",
    correctAnswer: "számítógépet",
    translation: "Computer",
  },
  { noun: "telefon", correctAnswer: "telefont", translation: "Phone" },
  { noun: "ablak", correctAnswer: "ablakot", translation: "Window" },
  { noun: "ajtó", correctAnswer: "ajtót", translation: "Door" },
  { noun: "város", correctAnswer: "várost", translation: "City" },
  { noun: "fény", correctAnswer: "fényt", translation: "Light" },
  { noun: "szoba", correctAnswer: "szobát", translation: "Room" },
  { noun: "zene", correctAnswer: "zenét", translation: "Music" },
  { noun: "alma", correctAnswer: "almát", translation: "Apple" },
  { noun: "kenyér", correctAnswer: "kenyeret", translation: "Bread" },
  { noun: "sütő", correctAnswer: "sütőt", translation: "Oven" },
  { noun: "játék", correctAnswer: "játékot", translation: "Game" },
  { noun: "film", correctAnswer: "filmet", translation: "Movie" },
  { noun: "tanár", correctAnswer: "tanárt", translation: "Teacher" },
  { noun: "diák", correctAnswer: "diákot", translation: "Student" },
  { noun: "csokoládé", correctAnswer: "csokoládét", translation: "Chocolate" },
  { noun: "kép", correctAnswer: "képet", translation: "Picture" },
  { noun: "hír", correctAnswer: "hírt", translation: "News" },
  { noun: "vállalat", correctAnswer: "vállalatot", translation: "Company" },
  { noun: "kávé", correctAnswer: "kávét", translation: "Coffee" },
  { noun: "szeretet", correctAnswer: "szeretetet", translation: "Love" },
  { noun: "terem", correctAnswer: "termet", translation: "Room" },
  { noun: "autóbusz", correctAnswer: "autóbuszt", translation: "Bus" },
  { noun: "tükör", correctAnswer: "tükröt", translation: "Mirror" },
  { noun: "hó", correctAnswer: "havat", translation: "Snow" },
  { noun: "sziget", correctAnswer: "szigetet", translation: "Island" },
];
