import { AccusativeChallengeQuestions } from "./AccusativeChallenge.types";

export const accusativeChallengeQuestions: AccusativeChallengeQuestions = [
  { noun: "kutya", correctAnswer: "kutyát", translation: "dog" },
  { noun: "macska", correctAnswer: "macskát", translation: "cat" },
  { noun: "autó", correctAnswer: "autót", translation: "car" },
  { noun: "ház", correctAnswer: "házat", translation: "house" },
  { noun: "szám", correctAnswer: "számot", translation: "number" },
  { noun: "könyv", correctAnswer: "könyvet", translation: "book" },
  { noun: "táska", correctAnswer: "táskát", translation: "bag" },
  { noun: "szék", correctAnswer: "széket", translation: "chair" },
  { noun: "asztal", correctAnswer: "asztalt", translation: "table" },
  { noun: "ember", correctAnswer: "embert", translation: "person" },
  { noun: "fa", correctAnswer: "fát", translation: "tree" },
  { noun: "kutatás", correctAnswer: "kutatást", translation: "research" },
  { noun: "ruha", correctAnswer: "ruhát", translation: "clothes" },
  { noun: "óra", correctAnswer: "órát", translation: "clock" },
  {
    noun: "számítógép",
    correctAnswer: "számítógépet",
    translation: "computer",
  },
  { noun: "telefon", correctAnswer: "telefont", translation: "phone" },
  { noun: "ablak", correctAnswer: "ablakot", translation: "window" },
  { noun: "ajtó", correctAnswer: "ajtót", translation: "door" },
  { noun: "város", correctAnswer: "várost", translation: "city" },
  { noun: "fény", correctAnswer: "fényt", translation: "light" },
  { noun: "szoba", correctAnswer: "szobát", translation: "room" },
  { noun: "zene", correctAnswer: "zenét", translation: "music" },
  { noun: "alma", correctAnswer: "almát", translation: "apple" },
  { noun: "kenyér", correctAnswer: "kenyeret", translation: "bread" },
  { noun: "sütő", correctAnswer: "sütőt", translation: "oven" },
  { noun: "játék", correctAnswer: "játékot", translation: "game" },
  { noun: "film", correctAnswer: "filmet", translation: "movie" },
  { noun: "tanár", correctAnswer: "tanárt", translation: "teacher" },
  { noun: "diák", correctAnswer: "diákot", translation: "student" },
  { noun: "csokoládé", correctAnswer: "csokoládét", translation: "chocolate" },
  { noun: "kép", correctAnswer: "képet", translation: "picture" },
  { noun: "hír", correctAnswer: "hírt", translation: "news" },
  { noun: "vállalat", correctAnswer: "vállalatot", translation: "company" },
  { noun: "kávé", correctAnswer: "kávét", translation: "coffee" },
  { noun: "szeretet", correctAnswer: "szeretetet", translation: "love" },
  { noun: "terem", correctAnswer: "termet", translation: "room" },
  { noun: "autóbusz", correctAnswer: "autóbuszt", translation: "bus" },
  { noun: "tükör", correctAnswer: "tükröt", translation: "mirror" },
  { noun: "hó", correctAnswer: "havat", translation: "snow" },
  { noun: "sziget", correctAnswer: "szigetet", translation: "island" },
];
