import { AccusativeChallengeQuestions } from "./AccusativeChallenge.types";

export const accusativeChallengeQuestions: AccusativeChallengeQuestions = [
  { noun: "Kutya", answer: "Kutyát", translation: "Dog" },
  { noun: "Macska", answer: "Macskát", translation: "Cat" },
  { noun: "Autó", answer: "Autót", translation: "Car" },
  { noun: "Ház", answer: "Házat", translation: "House" },
  { noun: "Szám", answer: "Számot", translation: "Number" },
  { noun: "Könyv", answer: "Könyvet", translation: "Book" },
  { noun: "Táska", answer: "Táskát", translation: "Bag" },
  { noun: "Szék", answer: "Széket", translation: "Chair" },
  { noun: "Asztal", answer: "Asztalt", translation: "Table" },
  { noun: "Ember", answer: "Embert", translation: "Person" },
  { noun: "Fa", answer: "Fát", translation: "Tree" },
  { noun: "Kutatás", answer: "Kutatást", translation: "Research" },
  { noun: "Ruha", answer: "Ruhát", translation: "Clothes" },
  { noun: "Óra", answer: "Órát", translation: "Clock" },
  { noun: "Számítógép", answer: "Számítógépet", translation: "Computer" },
  { noun: "Telefon", answer: "Telefont", translation: "Phone" },
  { noun: "Ablak", answer: "Ablakot", translation: "Window" },
  { noun: "Ajtó", answer: "Ajtót", translation: "Door" },
  { noun: "Város", answer: "Várost", translation: "City" },
  { noun: "Fény", answer: "Fényt", translation: "Light" },
  { noun: "Szoba", answer: "Szobát", translation: "Room" },
  { noun: "Zene", answer: "Zenét", translation: "Music" },
  { noun: "Alma", answer: "Almát", translation: "Apple" },
  { noun: "Kenyér", answer: "Kenyeret", translation: "Bread" },
  { noun: "Sütő", answer: "Sütőt", translation: "Oven" },
  { noun: "Játék", answer: "Játékot", translation: "Game" },
  { noun: "Film", answer: "Filmet", translation: "Movie" },
  { noun: "Tanár", answer: "Tanárt", translation: "Teacher" },
  { noun: "Diák", answer: "Diákot", translation: "Student" },
  { noun: "Csokoládé", answer: "Csokoládét", translation: "Chocolate" },
  { noun: "Kép", answer: "Képet", translation: "Picture" },
  { noun: "Hír", answer: "Hírt", translation: "News" },
  { noun: "Vállalat", answer: "Vállalatot", translation: "Company" },
  { noun: "Kávé", answer: "Kávét", translation: "Coffee" },
  { noun: "Szeretet", answer: "Szeretetet", translation: "Love" },
  { noun: "Terem", answer: "Termet", translation: "Room" },
  { noun: "Autóbusz", answer: "Autóbuszt", translation: "Bus" },
  { noun: "Tükör", answer: "Tükröt", translation: "Mirror" },
  { noun: "Hó", answer: "Havat", translation: "Snow" },
  { noun: "Sziget", answer: "Szigetet", translation: "Island" },
];
